---
# - name: copy config files to nginx (green) (sites-available)
#   copy:
#     src: green_conf
#     dest: /etc/nginx/sites-available/
# - name: copy config files to nginx (blue) (sites-available)
#   copy:
#     src: blue_conf
#     dest: /etc/nginx/sites-available/
# - name: set initial config (set route to green)
#   file:
#     src: /etc/nginx/sites-available/green_conf
#     dest: /etc/nginx/sites-enabled/green_conf
#     state: link
- name: template config file to reverse-proxy
  # vars:
  #   host_ip: "{{ green }}"
  #   host_port: 80
  include_vars:
      file: common_vars.yaml
      name: common
  template:
      src: conf.j2
      dest: /etc/nginx/sites-available/conf


...
