---
# - name: copy config files to nginx (green) (sites-available)
#   copy:
#     src: green_conf
#     dest: /etc/nginx/sites-available/
# - name: copy config files to nginx (blue) (sites-available)
#   copy:
#     src: blue_conf
#     dest: /etc/nginx/sites-available/
# - name: set initial config (set route to green)
#   file:
#     src: /etc/nginx/sites-available/green_conf
#     dest: /etc/nginx/sites-enabled/green_conf
#     state: link

  # vars:
  #   host_ip: "{{ green }}"
  #   host_port: 80
- name: include hosts (active, idle)
  include_vars:
      file: green_blue_vars.yaml
      name: green_blue
- name: print variable
  debug:
        msg: "Hello {{green_blue['active_host'] }} world!"
- name: template config file to reverse-proxy
  template:
      src: conf.j2
      dest: /etc/nginx/sites-available/conf


...
